### ISSUE TITLE
Password is echoed

### ISSUE THREAD

**Issue by drknexus** [eddelbuettel/rcppredis#12]
One problem I rediscovered with https://github.com/eddelbuettel/rcppredis/pull/11 is that when an auth provided password is provided, then is echoed to the console.  In redisConnect I handled that by wrapping the constructor in base::capture.output(), but that isn't applicable now.  Any ideas on how to suppress it?

**Comment by eddelbuettel** [comment]
Eeek.  That sounds bad.  In the 'redis is echoing back what we gave it' sense?

**Comment by eddelbuettel** [comment]
Wait a second.  Is this a simple oversight [from this line](https://github.com/eddelbuettel/rcppredis/blob/master/src/Redis.cpp#L58)?

**Comment by drknexus** [comment]
Just tested it.  Problem is resolved.  You're right - that was the source of the unexpected echo a very unfortunate appendix left over from debugging on my end.  Sorry about that.

**Comment by eddelbuettel** [comment]
I believe this took care of it:
- I set up `requirepassword` in the config (with the default)
- It now works as expected, see below.

```{r}
R> library(RcppRedis)
R> redis <- new(Redis, "localhost", 6379, "foobared")
R> redis
C++ object <0x1e80a10> of class 'Redis' <0x2648170>
R> redis2 <- new(Redis)
R> redis$exec("ping")
[1] "PONG"
R> redis2$exec("ping")
[1] "NOAUTH Authentication required."
R> 
```

**Comment by eddelbuettel** [comment]
No worries.  Been there, done that :)

Is the ChangeLog entry ok?  I am not inadvertently disclosing IDs or email -- that was all already in the git commit log ...

**Comment by drknexus** [comment]
The ChangeLog entry looks great.  No changes needed.
