### ISSUE TITLE
API is incomplete

### ISSUE THREAD

**Issue by russellpierce** [eddelbuettel/rcppredis#17]
It might be possible to process the Redis documentation JSON to create a full set of API functions.  We could avoid collision with existing functionality by making all calls all capitals.  However, because Cpp has strict typing, it might be a lot easier to write in a way that works by having the code that provides those functions written in R; that might involve encapsulating the RcppRedis constructor in some R code so that we can add functions to the resulting object.  All such functions would probably dispatch to execv in the Cpp code.

**Comment by eddelbuettel** [comment]
We could keep this open under 'wishlist' and review once @richfitz releases his API layer.

**Comment by drknexus** [comment]
See https://github.com/ropensci/RedisAPI/issues/7#issuecomment-160150675 for a solution by @richfitz; we'll revisit when RedisAPI layer hits CRAN.

**Comment by eddelbuettel** [comment]
Nice. Just commented there too.

**Comment by eddelbuettel** [comment]
Closing as stale.
