### ISSUE TITLE
RcppRedis could leak connections

### ISSUE THREAD

**Issue by drknexus** [eddelbuettel/rcppredis#19]
A daughter issue to https://github.com/eddelbuettel/rcppredis/issues/17.

There is no way currently to cleanly close a redis connection.  Some combination of CLIENT SETNAME/GETNAME and CLIENT KILL could avoid this.  In practice, it probably isn't very important to solve because we tend to build a redis connection and to keep using it.

**Comment by drknexus** [comment]
Actually with some additional testing, I'm not sure this is an issue.  Maybe the destructor being called is enough to handle the issue?

**Comment by eddelbuettel** [comment]
:+1:
