### ISSUE TITLE
On constructing connection timeout values less than 1 can cause freeze

### ISSUE THREAD

**Issue by russellpierce** [eddelbuettel/rcppredis#26]
Observed behavior:  Sometimes RcppRedis does not obey the timeout and locks the R process.
Desired behavior:  RcppRedis obeys timeout and produces error

Minimal example, something like:

```
library(RcppRedis)

options(redisRAMCache.host = "hostWithRunningRedisServer.com")
options(redisRAMCache.port=6379)
redisRAMCache <- new(Redis, getOption("redisRAMCache.host"), getOption("redisRAMCache.port"),"",2.0)

options(redisREcho.host = "hostWithoutRedisServer.com")
options(redisREcho.port=6379)
try(redisREcho <- new(Redis, getOption("redisREcho.host"),getOption("redisREcho.port"),"",0.5),silent=TRUE)
```

Except it seems like this edge case only gets hit sometimes and not in a way that is fully reproducable.  This is a stub if anyone else encounters similar behavior perhaps they can narrow it down further.

It seems specific to the case where the 2nd server isn't there and may require that the first server have established a connection already.

When the timeout is above 1, I've never been able to replicate the issue.

**Comment by eddelbuettel** [comment]
Closing as stale.
