### ISSUE TITLE
redis connection not auto reconnect after fork

### ISSUE THREAD

**Issue by bluaze** [eddelbuettel/rcppredis#31]
it would be better if redis connection could auto reconnect after fork when redis is used as shared memory for multicore style parallel computing.

**Comment by eddelbuettel** [comment]
I suppose.  Any idea how to implement that?

OTOH one can just get a new object in each worker:

```r
R> library(RcppRedis)
R> library(parallel)
R> res <- mclapply(1:4, function(i) { nr <- new(Redis, "localhost"); length(nr$keys("*")); })
R> res
[[1]]
[1] 68

[[2]]
[1] 68

[[3]]
[1] 68

[[4]]
[1] 68

R> 
```

**Comment by bluaze** [comment]
Actually, I have no idea about how to do it. I just have read some article recommending not to manually manage connections, such as http://sorentwo.com/2015/08/25/managing-redis-reconnections-from-ruby.html

**Comment by eddelbuettel** [comment]
I think for now the simplest approach is to re-create a connection as I did there.  I leave this open as unfixed.

**Comment by russellpierce** [comment]
I'm late to the party, but FWIW in my own code I've handled this by wrapping the Redis connection up inside an R6 object that is PID aware.  When the PID changes, I rebuild the connection.  I'd briefly considered committing something along those lines here a while back, but it seems as though RcppRedis is meant to stay pretty purely Rcpp without a bunch of extra R cruft.

**Comment by eddelbuettel** [comment]
Ah, well, we could. If there is a use case, and ideally a test case.

I don't seem to need it. Many of my clients to Redis are shiny apps which seem to stay connected "forever". 

But we can discuss.

**Comment by eddelbuettel** [comment]
Closing as stale.
