### ISSUE TITLE
Should listen be an internal method?

### ISSUE THREAD

**Issue by eddelbuettel** [eddelbuettel/rcppredis#49]
In other words make it `.listen()` and also drop the help page?  Is it useful for users or just used inside `redisMonitorChannels()` ?

**Comment by bwlewis** [comment]
Yeah, we can do that too of course.

Sorry for all the PRs.

**Comment by eddelbuettel** [comment]
Not a problem at all.  Do you want to fold that into the open PR?   Or we can do another -- sorry for me pushing in master which lead to the need for rebase (or squashing).

**Comment by bwlewis** [comment]
Yeah, leave it open for a while...

**Comment by eddelbuettel** [comment]
Or we can do a number of small ones.  Either way is fine....

**Comment by eddelbuettel** [comment]
And merged -- thanks again for all this.  More to do, at least on the publicising front.  Will aim to write a blog post.
